version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - chmod +x mvnw

  build:
    commands:
      - echo Build Started
      - ./mvnw clean package

artifacts:
  files:
    - target/*.jar